# Generated by Django 4.2.4 on 2023-08-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0002_tournament_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
    ]
