# Generated by Django 4.2.4 on 2023-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0003_remove_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('I', 'interantional'), ('N', 'national')], max_length=1, null=True),
        ),
    ]
