# Generated by Django 4.2.4 on 2023-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0004_tournament_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=100, null=True)),
                ('photos', models.ImageField(null=True, upload_to='')),
                ('social_insta', models.CharField(max_length=100, null=True)),
                ('social_fb', models.CharField(max_length=100, null=True)),
                ('social_profile', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
