# Generated by Django 4.2.4 on 2023-08-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0006_alter_photos_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='GalleryPhoto',
        ),
    ]
