# Generated by Django 4.2.4 on 2023-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0007_rename_photos_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamee', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
