# Generated by Django 4.2.4 on 2023-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0009_delete_testtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100, null=True)),
                ('news_desc', models.TextField(max_length=1000, null=True)),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='social_fb',
            new_name='fb',
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='photos',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='social_insta',
            new_name='insta',
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='social_profile',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='phot_desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='tweet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
