# Generated by Django 4.2.4 on 2023-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0010_news_rename_social_fb_galleryphoto_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(null=True),
        ),
    ]
