# Generated by Django 4.2.4 on 2023-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0011_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_desc',
            field=models.TextField(null=True),
        ),
    ]
