# Generated by Django 4.2.4 on 2023-08-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0012_alter_news_news_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
    ]
