# Generated by Django 4.2.4 on 2023-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0016_contact_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100, null=True)),
                ('video_desc', models.TextField(null=True)),
                ('g_video', models.ImageField(null=True, upload_to='videos/')),
                ('date_added', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='phot_desc',
            field=models.TextField(null=True),
        ),
    ]
