# Generated by Django 4.2.4 on 2023-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six_a_side', '0017_galleryvideo_galleryphoto_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryvideo',
            name='g_video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
